maindjango/maindjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.urls import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', admin.site.urls),
    
    path('', include('review.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path("__reload__/", include("django_browser_reload.urls")),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

maindjango/review/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('review/', views.review_list, name='review_list'),
    path('', views.review_list, name='review_list'),
    path('create/', views.review_create, name='review_create'),
    path('<int:review_id>/edit/', views.review_edit, name='review_edit'),
    path('<int:review_id>/delete/', views.review_delete, name='review_delete'),
    path('my_reviews/', views.my_reviews, name='my_reviews'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('register/', views.register, name='register'),
    
] 

maindjango/review/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Review(models.Model):
    RATING_CHOICES = [
        (1, '1 - Poor'),
        (2, '2 - Fair'),
        (3, '3 - Good'),
        (4, '4 - Very Good'),
        (5, '5 - Excellent'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video_title = models.CharField(max_length=500, default='Unknown Title')
    video_url = models.URLField(max_length=2000,default='Unknown URL')
    text = models.TextField(max_length=2000)
    photo = models.ImageField(upload_to='photos/', blank=True,null=True)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, default=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.user.username} - Rating: {self.rating} - {self.text[:100]}...'

        

    
    

maindjango/review/forms.py
from django import forms
from .models import Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['video_title', 'video_url','text','photo','rating']
        labels = {
            'video_title': 'Enter video name',
            'video_url': 'Enter video url',
            'text': 'Your Review',
            'photo': 'Upload an Image',
            'rating': 'Rate the Channel',
        }
        widgets = {
            'video_title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the title of the video',
                'maxlength': '255'
            }),
            'video_url': forms.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the URL of the video'
            }),
            'text': forms.Textarea(attrs={
                'rows': 5,
                'class': 'form-control',
                'placeholder': 'Write your review here...'
            }),
            'rating': forms.Select(choices=Review.RATING_CHOICES, attrs={
                'class': 'form-control'
            }),
            'photo': forms.ClearableFileInput(attrs={
                'class': 'form-control-file'
            }),
        }

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

maindjango/review/views.py
from django.shortcuts import render
from .models import Review
from .forms import ReviewForm, UserRegistrationForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib import messages


# Create your views here.
def index(request):
    return render(request, 'index.html')

def review_list(request):
    reviews = Review.objects.all().order_by('-created_at')
    return render(request, 'review_list.html', {'reviews' : reviews})

@login_required
def review_create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('review_list')
    else:
        form = ReviewForm()
    return render(request, 'review_form.html', {'form' : form})

@login_required
def review_edit(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user= request.user)
    if request.method =='POST':
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('review_list')
    else:
        form = ReviewForm(instance=review)
    return render(request,'review_form.html',{'form': form})

@login_required            
def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id, user= request.user)
    if request.method == 'POST':
        review.delete()
        return redirect('review_list')
    return render(request,'review_confirm_delete.html',{'review': review})

@login_required
def my_reviews(request):
    reviews = Review.objects.filter(user=request.user)
    return render(request, 'my_reviews.html', {'reviews': reviews})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            # print(user.username, user.password)
            return redirect('review_list')
               
    else:
        form = UserRegistrationForm()
    
    return render(request, 'registration/register.html',{'form':form})

maindjango/review/templates/index.html
{% extends "layout.html" %}

{% block title %}
Django Review Detail Page
{% endblock %}

{% block content %}
<div class="full_body">
    <h1 class="text-3xl text-red-500 flex items-center justify-center font-bold">test template</h1>

</div>
{% endblock %}
    
</body>
</html>

maindjango/review/templates/my_reviews.html
{% extends "layout.html" %}
{% block title %}My Reviews{% endblock %}

{% block content %}
<div class="review-list-container max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
    <h2 class="text-3xl text-white font-bold mb-8">My Reviews</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for review in reviews %}
            <div class="review-item bg-gray-800 rounded-2xl overflow-hidden shadow-2xl mt-2">
                <img class="w-full h-44 object-cover" src="{{ review.photo.url }}" alt="{{ review.video_title }}">
                <div class="p-4">
                    <h3 class="text-2xl text-orange-400 font-semibold mb-2">{{ review.video_title }}</h3>
                    <p class="text-gray-300 mb-4">{{ review.text }}</p>
                    <a href="{{ review.video_url }}" target="_blank" class="text-blue-300 underline hover:text-blue-500">
                        Watch Video
                    </a>
                    <a href="{% url 'review_list' %}" class="flex py-4 text-orange-400 hover:underline">Read More</a>
                </div>
            </div>
        {% empty %}
            <p class="text-white">You haven't submitted any reviews yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

maindjango/review/templates/review_confirm_delete.html
{% extends "layout.html" %}

{% block title %}
Django Review Page
{% endblock %}

{% block content %}
<div class="full_body">
    <h1 class="text-3xl text-red-500 flex items-center justify-center font-bold px-[100px]">Are you sure that you want to delete the review?</h1>
</div>

<form method="post">
    {% csrf_token %}
    <div class="del_canc flex justify-center items-center p-6 gap-4 font-bold text-gray-800">
        <button class="border rounded-xl p-3 bg-red-500">Delete</button>
        <a class="border rounded-xl p-3 bg-green-500" href="{% url 'review_list' %}">Cancel</a>
    </div>
</form>
{% endblock %}
    
</body>
</html>

maindjango/review/templates/review_form.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Django Review Page
{% endblock %}

{% block content %}
<div class="full_body flex justify-center items-center flex-col">
    <h1 class="text-3xl text-red-500 flex items-center justify-center font-bold px-[100px]">Review form page</h1>

    <h2 class="text-white text-3xl">
        {% if form.instance.pk %} 
        Edit Review
        {% else %}
        Add Review
        {% endif %}
    </h2>

    <form method="post" enctype="multipart/form-data" class="form bg-transparent border-gray-600  shadow-2xl p-8 flex justify-center items-center flex-col w-[40%]">
        
    {% csrf_token %}
    {{form.as_div}}
    <button class="hover:border p-2 bg-gray-500 w-[10rem] hover:bg-gray-700 text-white font-semibold text-xl border-gray-500 border-none rounded" type="submit">Submit</button>
    </form>

    <a class='text-white m-4 text-xl' href="{% url 'review_list' %}">Back to Review list Hub</a>
</div>
{% endblock %}
    
</body>
</html>

maindjango/review/templates/review_list.html
{% extends "layout.html" %}

{% block title %}
Django Review List Page
{% endblock %}

{% block content %}
<div class="py-10">
    <h1 class="text-4xl text-red-500 font-bold text-center mb-8">Review List Hub</h1>

    <a href="{% url 'review_create' %}" class="block text-amber-100 bg-blue-600 hover:bg-blue-700 px-6 py-3 rounded-lg text-lg font-semibold mb-8 mx-auto w-max text-center shadow-gray-700 shadow-2xl">Write a Review</a>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mx-4">
        {% for review in reviews %}
        <div class="bg-gray-700 text-white rounded-lg shadow-lg transition-transform transform hover:scale-105 hover:bg-gray-600 p-6">
            <div class="flex flex-col justify-between h-full">
                <div>
                    <h5 class="text-gray-200 text-xl font-bold mb-2">{{ review.user.username|capfirst }}</h5>
                    <h6 class="text-lg font-semibold text-blue-300 mb-2">{{ review.video_title }}</h6>
                    <p class="text-white mb-4">{{ review.text }}</p>
                    <a href="{{ review.video_url }}" target="_blank" class="text-pink-500 ">
                        Watch Video
                    </a>
                    <p class="text-green-300 mb-4">Rating Given: {{ review.get_rating_display }}</p>

                </div>
                {% comment "only logged in user  can edit and delete their reviews" %}{% endcomment %}
                <div class="flex justify-between mt-auto">
                    {% if review.user == user%}
                    <a href="{% url 'review_edit' review.id %}" class="text-white border p-2 w-20 text-center rounded-xl bg-blue-600 hover:bg-blue-700 font-semibold">Edit</a>
                    <a href="{% url 'review_delete' review.id %}" class="text-white border p-2 w-20 text-center rounded-xl bg-red-500 hover:bg-red-600 font-semibold">Delete</a>
                    {% endif%}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

maindjango/templates/layout.html
{% load static tailwind_tags %}
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Review Management system
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'form.css' %}">
    {% tailwind_css %}
</head>

<body class="bg-gray-800">
    <div class="pt-3 mb-4 shadow-xl">
        <div class="flex justify-between items-center px-[100px] w-full h-auto">
            <div class="logo text-[#ff5353] font-mono text-2xl font-bold cursor-pointer relative">
                <a href="#" class="flex items-center">
                    
                    <span class="text-[#ff5353]">Review </span>
                    <span class="text-orange-400 animate-bounce">.</span>
                </a>
            </div>
            <nav>
                <div class="flex justify-between gap-4 items-center max-w-screen-xl mx-auto">
                    <a class="text-white font-bold text-lg hover:text-orange-400 transition duration-300 active" href="{% url 'review_list' %}">Home</a>
                    <a href="#">About Us</a>
                    <a href="#">Help/Support</a>
                    
                    {% if user.is_authenticated %}

                    <a href="{% url 'my_reviews' %}">My Reviews</a>
                    <form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="text-white  hover:text-orange-400 transition duration-300">
                            Logout
                        </button>
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}" class="text-white font-bold text-lg hover:text-orange-400 transition duration-300">
                        Login
                    </a>
                    <a href="{% url 'register' %}" class="text-white font-bold text-lg hover:text-orange-400 transition duration-300 ml-4">
                        Register
                    </a>
                    {% endif %}
                    
                    
                    
                </div>
            </nav>
        </div>
        <hr class='mt-4 border-[#9a9999af]'/>
    </div>
    
    {% block content %}{% endblock %}
</body>
</html>

maindjango/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>